"""
Guard against missing localization keys.

`LM.get()` falls back to returning the key itself, so a typo or a key that was
never added renders a raw identifier such as "download_complete" directly in
the UI. Nothing else in the suite catches that, so this test scans every
first-party source file for ``LM.get("key")`` and asserts the key exists in
``locales/en.json``.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXCLUDED_DIRS = {".venv", "venv", "build", "dist", "htmlcov", "__pycache__"}

# Matches LM.get("key") including calls whose key sits on the following line.
_CALL_PATTERN = re.compile(r"""LM\.get\(\s*["']([A-Za-z0-9_]+)["']""")
# Also matches the status_map-style indirection: {"x": "key"} entries are not
# distinguishable from data, so only direct LM.get calls are checked here.


def _english_keys() -> set[str]:
    return set(json.loads((ROOT / "locales" / "en.json").read_text(encoding="utf-8")))


def _source_files():
    for path in ROOT.rglob("*.py"):
        if any(part in EXCLUDED_DIRS for part in path.parts):
            continue
        if "tests" in path.parts:
            continue
        yield path


def test_every_referenced_locale_key_exists_in_english():
    available = _english_keys()
    missing: dict[str, list[str]] = {}

    for path in _source_files():
        text = path.read_text(encoding="utf-8", errors="ignore")
        for key in _CALL_PATTERN.findall(text):
            if key not in available:
                missing.setdefault(key, []).append(str(path.relative_to(ROOT)))

    assert not missing, f"LM.get() keys missing from locales/en.json: {missing}"


def test_every_locale_covers_the_english_key_set():
    english = _english_keys()
    for locale_path in sorted((ROOT / "locales").glob("*.json")):
        if locale_path.name == "en.json":
            continue
        data = json.loads(locale_path.read_text(encoding="utf-8"))
        missing = sorted(english - set(data))
        assert not missing, f"{locale_path.name} is missing: {missing}"


def test_locale_files_are_sorted_and_indented_consistently():
    """Locale files are regenerated by tooling; keep them diff-friendly."""
    for locale_path in sorted((ROOT / "locales").glob("*.json")):
        raw = locale_path.read_text(encoding="utf-8")
        assert raw.endswith("\n"), f"{locale_path.name} must end with a newline"
        data = json.loads(raw)
        # Re-serialising with the project's settings must be a no-op
        assert (
            json.dumps(data, ensure_ascii=False, indent=2) + "\n" == raw
        ), f"{locale_path.name} is not formatted as expected"


class TestLocalizationGetCallSites:
    """``LM.get``'s positional extras are *format arguments*, not defaults.

    A string literal passed positionally gets interpolated into the template
    (``"{0} downloading".format("{0} downloading")``), which produced text like
    "3 downloading downloading" in the queue header. Fallbacks must use the
    ``default=`` keyword; this scan keeps new call sites honest.
    """

    ALIASES = {"LM", "LocalizationManager"}

    def _literal_default_calls(self):
        import ast
        from pathlib import Path

        root = Path(__file__).resolve().parent.parent
        offenders = []
        for path in sorted(root.rglob("*.py")):
            if any(part in {".venv", "tests", "build", "dist"} for part in path.parts):
                continue
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
            for node in ast.walk(tree):
                if not isinstance(node, ast.Call):
                    continue
                func = node.func
                if not isinstance(func, ast.Attribute) or func.attr != "get":
                    continue
                owner = func.value
                owner_name = getattr(owner, "id", None) or getattr(owner, "attr", None)
                if owner_name not in self.ALIASES:
                    continue
                if len(node.args) < 2:
                    continue
                second = node.args[1]
                if isinstance(second, ast.Constant) and isinstance(second.value, str):
                    offenders.append(
                        f"{path.relative_to(root)}:{node.lineno} -> "
                        f"LM.get({ast.unparse(node.args[0])!s}, {second.value!r})"
                    )
        return offenders

    def test_no_literal_positional_defaults(self):
        offenders = self._literal_default_calls()
        assert not offenders, (
            "Use default= for fallbacks; positional strings are format args:\n"
            + "\n".join(offenders)
        )

    def test_default_keyword_is_used_when_key_is_missing(self):
        from localization_manager import LocalizationManager

        saved_strings = dict(LocalizationManager._strings)
        saved_fallback = dict(LocalizationManager._fallback_strings)
        try:
            LocalizationManager._strings = {}
            LocalizationManager._fallback_strings = {}
            assert (
                LocalizationManager.get("definitely_missing_key", default="Fallback")
                == "Fallback"
            )
            # Without a default the key itself is surfaced (existing contract).
            assert LocalizationManager.get("definitely_missing_key") == (
                "definitely_missing_key"
            )
        finally:
            LocalizationManager._strings = saved_strings
            LocalizationManager._fallback_strings = saved_fallback
