# pylint: disable=all
from typing import Any

class Presence:
    def __init__(self, client_id: str): ...
    def connect(self) -> None: ...
    def update(self, **kwargs: Any) -> None: ...
    def clear(self) -> None: ...
    def close(self) -> None: ...
